dubbo:
  application:
    name: dtlab-user
    logger: slf4j
    serialize-check-status: WARN
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  provider:
    filter:  GlobalExceptionFilter, -exception

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dtlab
    password: dtlab
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}/dtlab?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

mqtt:
  broker:
    url: ${MQTT_URL:tcp://127.0.0.1:1883}
  username: ${MQTT_USERNAME:backend}
  password: ${MQTT_PASSWORD:backend}
  client:
    id: ${MQTT_CLIENTID:backend}
  topics: tracking/result
  qos: 1
  connectionTimeout: 5000
  keepAliveInterval: 60
